<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtyRkkw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtyRkkw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUtyRkkw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUtyRkkw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUtyRkkw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UtyRkkw',
    'container.build_id' => 'e48e1723',
    'container.build_time' => 1592901074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtyRkkw');
